server:
  port: 8080

spring:
  application:
    name: yorimichi


  web:
    resources:            # ✅ plural
      add-mappings: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yorimichi.duckdns.org:3306/yorimichi?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: jsl3team
    password: ${DB_PASSWORD}   # ✅ 환경변수로 주입 권장

  thymeleaf:
    cache: false

  security:
    user:
      name: admin
      password: 1234

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jslhrd.yorimichi.domain
